### ISSUE TITLE
Missing dots

### ISSUE THREAD

**Issue by mauro3** [luraess/parallel-gpu-workshop-JuliaCon21#3]
There are few places with missing `.`.  For instance:
- https://github.com/luraess/parallel-gpu-workshop-JuliaCon21/blob/d36accd85044641c0abe66b1c90f9eb9f24ce084/scripts/diffusion_2D_expl.jl#L33
- https://github.com/luraess/parallel-gpu-workshop-JuliaCon21/blob/d36accd85044641c0abe66b1c90f9eb9f24ce084/scripts/diffusion_2D_impl.jl#L41

**Comment by luraess** [comment]
Thanks for pointing this out.
